### ISSUE TITLE
Supporting '.js' imports

### ISSUE THREAD

**Issue by guybedford** [TypeStrong/ts-loader#1056]
TypeScript are currently recommending that the best way to handle Node.js ES module support output is to use explicit .js extensions in the imports, even between TypeScript files (see https://github.com/microsoft/TypeScript/issues/16577#issuecomment-309169829):

main.ts
```js
import dep from './dep.js';
```

dep.ts
```js
export default 'dependency';
```

This is the only pattern that guarantees that extensions are included in a tsc compilation, making the output work in Node.js modules.

I just tried this out with ts-loader in ncc, and am getting that this is not supported.

I think it would be ideal if this project could follow that same pattern.

**Comment by johnnyreilly** [comment]
If you'd like to send a PR that adds support we're open to it! Don't worry about tests initially - start with getting it working and I'll help out 🤗

**Comment by guybedford** [comment]
Closing as a non-bug since it appears this is working correctly after all!

**Comment by HKalbasi** [comment]
It isn't working. I need to use `"module": "ES2020",` in my tsconfig, for enabling top level await support of webpack, and I need to remove extensions for this plugin to work. Annoyingly, I have nodejs files in the same project and for that to work, I need to add extension to make nodejs ESM happy. So I need to remember which file is node and which file is browser. Since extensions are ES standard, I think I should solve the problem with webpack and this plugin.
