### ISSUE TITLE
[Question] Why is ts-loader ignoring my compilerOptions?

### ISSUE THREAD

**Issue by cerino-ligutom** [TypeStrong/ts-loader#1131]
For context, I'm using Vue bootstrapped with vue-cli and tried to use chain webpack as per [documentation](https://cli.vuejs.org/guide/webpack.html#modifying-options-of-a-loader)

I added a `vue.config.js` with the snippet below. The options seem to be acknowledged here but it doesn't override my tsconfig's `compilerOptions` during build. Am I missing something?

```js
const isProduction = process.env.NODE_ENV === 'production';

module.exports = {
	chainWebpack: (config) => {
		if (isProduction) {
			config.module
				.rule('ts')
				.use('ts-loader')
				.tap((options) => {
					// Temporary until vue-apollo issues gets fixed
					options.compilerOptions = {
						strict: false,
						noImplicitAny: false,
						noImplicitThis: false,
					};
					console.log('options:', options);
					return options;
				});

			config.module
				.rule('tsx')
				.use('ts-loader')
				.tap((options) => {
					// Temporary until vue-apollo issues gets fixed
					options.compilerOptions = {
						strict: false,
						noImplicitAny: false,
						noImplicitThis: false,
					};
					console.log('options:', options);
					return options;
				});
		}
	},
};
```

## Additional Info:

Here's what was logged by the console:
![image](https://user-images.githubusercontent.com/6721822/84126231-388c4f80-aa70-11ea-960c-d4cf7fdd5873.png)

As for folder structure, `vue.config.js` and `tsconfig.json` are both on the root directory. It keeps using my `tsconfig` for some reason despite the config above.

Tried inspecting the webpack produced by the vue cli and this is how it looks (tsx rule is pretty much the same):
![image](https://user-images.githubusercontent.com/6721822/84126762-eb5cad80-aa70-11ea-9440-4f2a1e572eb0.png)

If I set the properties in the config above to `false` in the `tsconfig.json` itself, I get the desired behavior which led me to this question.

**Comment by appzuka** [comment]
I'm not very experienced with Vue but I created a simple project and could observe what you are seeing.

I believe what might be happening is that Vue sets the transpileOnly and happyPackMode options on ts-loader to true.  This means ts-loader is only transpiling and will not report any type errors.  Vue appears to use a plugin, fork-ts-checker, to actually do the type checking.  Taking the type checking off the main thread should decrease build time.

So you need to pass the compiler options you need to fork-ts-checker in order to not see type errors.  I added the following to the vue.config.js and the errors went away:
```
    config.plugin('fork-ts-checker').tap((options) => {
      options[0].compilerOptions = {
        strict: false,
        noImplicitAny: false,
        noImplicitThis: false,
      };
      return options;
    });
```
Again, I'm not experienced with Vue so this may not be the correct format, but it makes sense and cures the problem.

If you are still having issues and can produce a minimal repo I'll take another look.

**Comment by cerino-ligutom** [comment]
That worked! Guess I was looking at the wrong thing. Thank you!
