### ISSUE TITLE
Ts-loader symlink via lerna yarn workspace failed to resolve dependencies outside of current workspace

### ISSUE THREAD

**Issue by dayrim** [TypeStrong/ts-loader#1145]
I have a monorepo with specific structure. But it appears to be unable to resolve modules which are in monorepo root. I get many errors of the kind. `Module not found: Error: Can't resolve 'tls' in 'C:\Users\msi4\monorepo\node_modules\nats\lib'` when building one of the projects in apps. Works with gulp or tsc, but not with webpack.

Project structure:
``` 
package.json
lerna.json
/node_modules 
/apps
  /project_a
    /node_modules
    webpack.config.js
    tsconfig.json
    package.json
  /project_b
    /node_modules
    webpack.config.js
    tsconfig.json
    package.json
/lib
  /package_a
    /node_modules
    webpack.config.js
    tsconfig.json
    package.json
  /package_b
    /node_modules
    webpack.config.js
    tsconfig.json
    package.json
```

tsconfig.json
``` json
{
  "compilerOptions": {
    "outDir": "dist",
    "rootDir": "src",
    "baseUrl": "src",

    "target": "es6",
    "module": "commonjs",
    "declaration": true,
    "declarationMap": true,
    "sourceMap": true,
    "strict": true,
    "composite": true,
    "esModuleInterop": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,

    "allowJs": true,
    "incremental": true,
    "moduleResolution": "node",
    "skipLibCheck": true
  },
  "include": ["src", "definitions"],
  "exclude": ["node_modules", "test", "dist", "**/*spec.ts"]
}

```

webpack.config.js

``` jasvascript
const path = require("path");

const { NODE_ENV = "development" } = process.env;

module.exports = {
  entry: {
    main: path.join(__dirname, "src/main.ts"),
  },
  output: {
    path: path.join(__dirname, "dist"),
    filename: "main.js",
  },
  module: {
    rules: [
      /* TS file loader */
      {
        test: /\.ts|\.tsx$/,
        exclude: /node_modules/,

        use: [
          {
            loader: "ts-loader",
          },
        ],
      },
    ],
  },
  resolve: {
    extensions: [
      "*",
      ".ts",
      ".tsx",
      ".mjs",
      ".js",
      ".json",
      ".json",
      ".gql",
      ".graphql",
    ],
  },

  mode: NODE_ENV,
};

```

Tried setting symlinks to false as per [webpack docs](https://webpack.js.org/configuration/resolve/#resolvesymlinks).

**Comment by appzuka** [comment]
If you can provide an example repo I will take a look.

**Comment by chanced** [comment]
@appzuka I think I am running into the same issue. https://github.com/chanced/ts-monorepo

**Comment by appzuka** [comment]
Hi @chanced,

Thanks for sharing your repo.  I took a look but was not able to run the command <code>yarn api compile</code> as the command compile cannot be found.  However, I guess yarn api compile just runs webpack in the api package directory.  When I do this I see the same error as you.

The error is complaining that you are importing a source file which is not under the rootDir.  Specifically:
```
ts-monorepo/packages/core/src/models/spike.ts
```
is not under
```
ts-monorepo/packages/api
```
The line causing this error is:
```
import { Spike } from "@ts-monorepo/core/models/spike";
```
You can import Spike directly from @ts-monorepo/core because it imports and re-exports from models/spike.  If you import from @ts-monorepo/core it will import from @ts-monorepo/core/dist/index.js because that is specified as main in package.json. Then there is no error because you are not using typescript source outside rootDir.  So if I change the line above to
```
import { Spike } from "@ts-monorepo/core";
```
and run webpack it builds without error.

I hope this helps.  Let me know if there are further issues.

**Comment by chanced** [comment]
>  I took a look but was not able to run the command yarn api compile as the command compile cannot be found. However, I guess yarn api compile just runs webpack in the api package directory. When I do this I see the same error as you.

Arg, I'm sorry about that! I was messing around with it and forgot I removed it. You're right in that it just runs webpack though. Thank you for taking the time to look at it!

I'm using `references` ([docs](https://www.typescriptlang.org/docs/handbook/project-references.html)) which should build that project. `tsc` doesn't have an issue with it, but fails at inferring the paths at runtime because it will not rewrite them in the output. That's where [tsconfig-paths](https://github.com/dividab/tsconfig-paths) / [tsconfig-paths-webpack](https://github.com/dividab/tsconfig-paths-webpack-plugin) come in.

**Comment by chanced** [comment]
@appzuka sorry, I forgot to @ you :)

**Comment by chanced** [comment]
The issue with using `@ts-monorepo/core` over `@ts-monorepo/core/models` is that by having index.ts `export * from './models'` is that code leaks. I realize this is probably not an ideal setup but for expediency, I have a monorepo with both client and serverside code, fullstack typescript. I reuse types from the server on the client but do not want certain packages to have their actual code exposed clientside.

The way yarn workspaces or lerna are designed, they expose the packages as a symlinked `node_module`. If there is an actual entry point on the package.json, then it can and is included in the project even if it is not explicitly stated.

For example, [web/pages/index.tsx](https://github.com/chanced/ts-monorepo/blob/master/packages/web/pages/index.tsx) is able to utilize `@ts-monorepo/core/models/Spike` even though `@ts-monorepo/core` was referenced in the web's [package.json](https://github.com/chanced/ts-monorepo/blob/master/packages/web/package.json) or the root project's [package.json](https://github.com/chanced/ts-monorepo/blob/master/package.json).

**Comment by chanced** [comment]
I was able to get mine working using the `projectReferences` option.

@appzuka Thanks 👍

**Comment by appzuka** [comment]
@chanced, If you include
```
"paths": {
  "@ts-monorepo/core/*": ["../core/src/*"],
}
```
in your tsconfig.json then you are linking to the ts code in the src folder of the core project.   As you are including core as a project reference then typescript will build the core project for you and put the compiled code and declaration files in core/dist.  Therefore you can point to the core/dist instead of the core/src:
```
"paths": {
  "@ts-monorepo/core/*": ["../core/dist/*"],
}
```
This will improve speed as you are not re-compiling code, but it will also eliminate the "[...] is not under 'rootDir'" error as you are not including any .ts files outside the rootDir.  It should then work with tsconfig-paths-webpack-plugin, but don't forget to provide the extensions option:
```
plugins: [new TsconfigPathsPlugin({
  extensions: [".ts", ".tsx", ".js"]
})],
```

**Comment by chanced** [comment]
@appzuka that's a good call for projects that just reference it for types. Thanks!

**Comment by DiFuks** [comment]
I have a similar problem. Here is the repository with playback:

https://github.com/DiFuks/ts-references

`yarn tsc` - working
`yarn ts-node` - working
`yarn webpack:babel-loader` - working
`webpack:ts-loader` - not working :(

At the same time, with [such an edit](https://github.com/DiFuks/ts-references/commit/622bc4a62554d834acfbe9eb9d058125a4d6eab1), everything starts to work. But in this case `main` uses the uncompiled version of `submodule`

**Comment by DiFuks** [comment]
[This workaround](https://github.com/DiFuks/ts-references/commit/500396d5b1d77121e161afd3a508b8f422c69786)  also works

**Comment by DiFuks** [comment]
This issue reproduces with yarn 3 + pnp
