### ISSUE TITLE
ts-loader must be restarted for new files to be compiled

### ISSUE THREAD

**Issue by berickson1** [TypeStrong/ts-loader#1179]
In my project that utilizes project references (likely relevant), adding new files requires a full restart of webpack to detect them. This occurs if experimentalWatchApi flag is both turned on or off.

I've included a complete repro below. As far as I can tell, I'm not doing anything out of the ordinary but would appreciate guidance here if I am!

### Expected Behaviour
Adding a new file (foo.ts) and importing it from an existing file (dog.ts) results in a clean build

### Actual Behaviour
The compiler indicates that foo.ts is not included in the project, even though the tsconfig.json includes it. Restarting webpack will result in a clean build.

ERROR in /src/project-references-demo/animals/dog.ts
./animals/dog.ts
[tsl] ERROR in /src/project-references-demo/animals/dog.ts(3,21)
      TS6307: File '/src/project-references-demo/animals/foo.ts' is not listed within the file list of project '/src/project-references-demo/animals/tsconfig.json'. Projects must list all files or use an 'include' pattern.

### Steps to Reproduce the Problem
1) Clone repo below
2) Run `npm install`, `npm run webpack`
3) Observe clean webpack build
4) Rename 'animals/foo.renametots` to `animals/foo.ts`
5) Uncomment lines 3&4 in `animals/dog.ts`
6) Observe webpack output

### Location of a Minimal Repository that Demonstrates the Issue.
https://github.com/berickson1/project-references-demo/tree/newFileNotDetected

**Comment by appzuka** [comment]
I downloaded the repo and can confirm your findings. I can also confirm the same happens if you run plain <code>tsc -b -w -v</code> in the <code>animals</code> folder. It seems this is the behaviour of <code>tsc --build</code>.  TypeScript with projectReferences calls the same code as the command <code>tsc --build</code> via the TypeScript API so it is not surprising they behave the same.

Perhaps this should be logged as an issue on TypeScript. I assume the majority of development involves modifying files so if we need to restart when adding new files that might not be critical, as long as the behaviour is documented.

I have spent a while working with ts-loader and project references and have written a guide to document my findings.  You can read it at:

https://medium.com/@nickexcell/using-typescript-project-references-with-ts-loader-and-webpack-part-1-5d0c3cd7c603

I will be including this information and the example repo in ts-loader's documentation.

Lastly, I have also spent time working with experimentalWatchApi and would recommend staying away from it until someone can provide an example of it improving the build process.

**Comment by berickson1** [comment]
Good catch, I'll open an issue on typescript itself and link it to this.
Unfortunately our cold build times are...poor.. at the moment (~2.5 minutes vs several second incremental build), so adding or refactoring is a big pain (we're continually adding new react components, so it's a common scenairo)

**Comment by berickson1** [comment]
Actually, I'll maybe ask you to try that again. From the project root, I ran `npm run build -- -w`. The resulting build was clean after following the repro steps above. Below is the log. So the typescript compiler by itself is behaving as expected here for me.
```
> project-references-demo@1.0.0 build /src/project-references-demo
> tsc -b -v "-w"

c1:54:53 PM - Starting compilation in watch mode...

1:54:53 PM - Projects in this build: 
    * core/tsconfig.json
    * animals/tsconfig.json
    * zoo/tsconfig.json
    * tsconfig.json

1:54:53 PM - Project 'core/tsconfig.json' is up to date because newest input 'core/utilities.ts' is older than oldest output 'lib/core/utilities.js'

1:54:53 PM - Project 'animals/tsconfig.json' is out of date because oldest output 'lib/animals/animal.js' is older than newest input 'animals/dog.ts'

1:54:53 PM - Building project '/src/project-references-demo/animals/tsconfig.json'...

1:54:53 PM - Updating unchanged output timestamps of project '/src/project-references-demo/animals/tsconfig.json'...

1:54:53 PM - Project 'zoo/tsconfig.json' is up to date with .d.ts files from its dependencies

1:54:53 PM - Updating output timestamps of project '/src/project-references-demo/zoo/tsconfig.json'...


1:54:53 PM - Found 0 errors. Watching for file changes.
c1:54:59 PM - File change detected. Starting incremental compilation...

1:54:59 PM - Project 'animals/tsconfig.json' is out of date because oldest output 'lib/animals/animal.js' is older than newest input 'animals/foo.ts'

1:54:59 PM - Building project '/src/project-references-demo/animals/tsconfig.json'...

1:54:59 PM - Updating unchanged output timestamps of project '/src/project-references-demo/animals/tsconfig.json'...

1:54:59 PM - Project 'zoo/tsconfig.json' is up to date with .d.ts files from its dependencies

1:54:59 PM - Updating output timestamps of project '/src/project-references-demo/zoo/tsconfig.json'...


1:55:00 PM - Found 0 errors. Watching for file changes.
c1:55:04 PM - File change detected. Starting incremental compilation...

1:55:04 PM - Project 'animals/tsconfig.json' is out of date because oldest output 'lib/animals/animal.js' is older than newest input 'animals/dog.ts'

1:55:04 PM - Building project '/src/project-references-demo/animals/tsconfig.json'...

1:55:04 PM - Updating unchanged output timestamps of project '/src/project-references-demo/animals/tsconfig.json'...

1:55:04 PM - Project 'zoo/tsconfig.json' is up to date with .d.ts files from its dependencies

1:55:04 PM - Updating output timestamps of project '/src/project-references-demo/zoo/tsconfig.json'...


1:55:05 PM - Found 0 errors. Watching for file changes.
```

**Comment by appzuka** [comment]
I still get the same error, even running from the root folder, but I found some interesting behaviour.

I usually develop in Windows using WSL2.  I tried the same using Powershell and I noticed that when I rename <code>foo.renametots</code>, tsc immediately rebuilds, without error.  When I then change <code>dog.ts</code> there is no error because <code>tsc</code> has already seen <code>foo.ts</code>.

Using WSL, there is no rebuild when I rename <code>foo.renametots</code>.  The rebuild first starts when I save the new <code>dog.ts</code>, which then fails because <code>foo.ts</code> is not part of the compilation.

I guess this could be a timing issue, depending on whether <code>tsc -b -w</code> registers the new file or the changed file first. I'm not sure why, under Powershell, tsc rebuilds when a new file is added to the path, even though that file was not part of the compilation at that time. Or perhaps this is correct and tsc under WSL should have noticed the new file and triggered a rebuild.

It feels to me as if this is a behaviour of <code>tsc</code> and should be fixed there.

**Comment by berickson1** [comment]
Maybe that's the difference here. I'm running this on MacOS. I can bring up a windows environment and try it there.

**Comment by berickson1** [comment]
Running `npm run build -- -w` in `cmd` on Windows 10, node 12.16.2 and making the above changes described results in a clean build. Running under webpack + ts-loader results in the "broken" behaviour.  Tried the same under powershell and the result is consistent with my original issue/repro.

I also spun up a WSL environment and am seeing the exact same. (node 14.9.0) - Rebuild on rename, rebuild on change to dog.ts. Successful build both times

I struggle to open a typescript issue myself when I'm unable to create a local repro of the issue. Based on everything I've seen locally, there doesn't seem to be an issue with tsc itself.

**Comment by appzuka** [comment]
When I try <code>tsc -b -v -w</code> again using your repo using WSL2 and TypeScript 3.9.6 I still do not see a rebuild when a file is renamed.  However, when I upgraded TypeScript to 4.0.2 I do see the rebuild on rename.  With webpack + ts_loader it still requires a restart.  Without digging through the code I assume that when ts-loader uses the tsc API it does not refresh the file list after webpack starts.

I would suggest asking those who worked on adding project references to ts-loader (@andrewbranch, @sheetalkamat I believe) to comment as they may understand what is going on and if there is a quick fix.

**Comment by berickson1** [comment]
Some additional context here: New files are tracked if they're added in `zoo`, the top level project, but not in any of the other referenced projects.

Dumping the `configParseResult` in `instances.ts:successfulTypeScriptInstance` gives the following object, which only appears to have include paths for the `zoo` directory
```json
{
  options: {
    declaration: true,
    target: 1,
    module: 1,
    strict: true,
    noUnusedLocals: true,
    noUnusedParameters: true,
    noImplicitReturns: true,
    noFallthroughCasesInSwitch: true,
    composite: true,
    outDir: '/src/project-references-demo/lib/zoo',
    rootDir: '/src/project-references-demo/zoo',
    configFilePath: '/src/project-references-demo/zoo/tsconfig.json'
  },
  watchOptions: undefined,
  fileNames: [ '/src/project-references-demo/zoo/zoo.ts' ],
  projectReferences: [
    {
      path: '/src/project-references-demo/animals',
      originalPath: '../animals',
      prepend: undefined,
      circular: undefined
    }
  ],
  typeAcquisition: { enable: false, include: [], exclude: [] },
  raw: {
    extends: '../tsconfig-base.json',
    compilerOptions: { outDir: '../lib/zoo', rootDir: '.' },
    references: [ [Object] ],
    include: [ '**/*', '**/*.json' ],
    compileOnSave: false
  },
  errors: [],
  wildcardDirectories: { '/src/project-references-demo/zoo': 1 },
  compileOnSave: false,
  configFileSpecs: {
    filesSpecs: undefined,
    includeSpecs: [ '**/*', '**/*.json' ],
    excludeSpecs: [ '../lib/zoo' ],
    validatedIncludeSpecs: [ '**/*', '**/*.json' ],
    validatedExcludeSpecs: [ '../lib/zoo' ],
    wildcardDirectories: { '/src/project-references-demo/zoo': 1 }
  }
}
```

**Comment by berickson1** [comment]
Re-tested this with latest ts-loader and typescript - all seems well

**Comment by johnnyreilly** [comment]
Excellent - you can thank @sheetalkamat for that! ❤️

**Comment by youngderekm** [comment]
I still run into this issue.  webpack 5 + ts-loader, using project references.  New file in one of the referenced projects.  It can cause the TS6307 error.  Restart dev server and it works again.
