### ISSUE TITLE
Sourcemaps do not work when using multiple entry points

### ISSUE THREAD

**Issue by abettadapur** [TypeStrong/ts-loader#1185]
I am seeing a strange behavior, where using multiple entry points in Webpack causes source-maps to not work correctly. Here is a Github repo showing the problem: https://github.com/abettadapur/ts-loader-sourcemap-demo

* In the working directory, `entry` is set to `./src/index.ts`. The resulting source-map file has all the right sources.
```
dist/main.map.js
..."sources":["webpack:///webpack/bootstrap","webpack:///./src/index.ts","webpack:///./src/foo.ts"]...
```

* In the `not-working` directory, `entry` is set to `{index: './src/index.ts'}`. The resulting source-map file has the wrong source, `main.js`, and I have no idea where this is even coming from, as it's not even specified in the configuration.

```
dist/index.map.js
...,"sources":["webpack:///main.js"]...
```

For both setups, the compiled output is identical (except for the source map comment)
### Expected Behaviour
Source maps should work in both cases
### Actual Behaviour
Source maps only work when specifying a single entry point
### Steps to Reproduce the Problem
See above
### Location of a Minimal Repository that Demonstrates the Issue.
https://github.com/abettadapur/ts-loader-sourcemap-demo

**Comment by appzuka** [comment]
I believe this is a feature of webpack.  See the documentation for devtoolNamespace:

https://webpack.js.org/configuration/output/#outputdevtoolnamespace

If you change your src files from .ts to .js the behaviour is the same, showing ts-loader is not the issue.

**Comment by abettadapur** [comment]
Thanks @appzuka 
Changing this field did not change the behavior, it only prepended the `devtoolNamespace` to the sources file

```
output: {devtoolNamespace: "foo"}

// index.js.map
"sources":["webpack://foo/main.js"]...
```

**Comment by abettadapur** [comment]
As well, changing the extensions to `.js` and running them through `babel-loader`, with no other configuration changes, produces the correct result. Are you sure `ts-loader` is not involved here?

**Comment by appzuka** [comment]
I played around some more and saw some strange and inconsistent behaviour.  I changed the source to <code>.js</code> to take <code>ts-loader</code> out of the equation and still saw the issues.

I saw broken behaviour when changing the value of the entry.  So, for example, when I load your repo cleanly and run <code>npx webpack</code> I do **not** see the error, even in the <code>not working</code> folder.  When I change the name of the entry I do see the error, so if I change the <code>entry</code> option from <code>{index: ".src/index.js:}</code> to <code>{newname: ".src/index.js:}</code> then the output is broken.  The filename in the sourceMap is just <code>index.js</code>.  I believe it is getting the filename 'index' from the name of the entry, which was 'index' before it was changed to 'newname'.

This explains why you were seeing 'main.js'.  When the entry was just a string it was given the default name 'main'.  When you changed it to <code>{index: ".src/index.js:}</code> it remembered the name 'main' from the first run.  The problem does not seem to caused by going from single to multiple entry points but from changing the name of the entry point.

I believe webpack is remembering the name by in the folder <code>node_modules/.cache/terser-webpack-plugin</code>.  If you delete this folder the build will work next time, until you change the module name again. You can also get the correct behaviour by adding the following to webpack.config.js:
```
    optimization: {
      minimize: false,
    },
```
I assume you could also get the same by disabling the cache in terser-webpack-plugin.

I suggest you play around changing the name of the key in the entry object, deleting the .cache folder and stopping terser-webpack-plugin caching the modules.  Because the behaviour is inconsistent it can be hard to tell what is causes the problem and what does not.  If you find the same behaviour I suggest you raise and issue with webpack.

**Comment by abettadapur** [comment]
Thanks for taking a look. 
I ended up solving the issue by downgrading the `terser-webpack-plugin`, which solved my issue. Looks like some bug with the minifier

Thanks for taking a look
