### ISSUE TITLE
The syntax of the pipeline operator cannot be supported.

### ISSUE THREAD

**Issue by LP1994** [TypeStrong/ts-loader#1191]
Expected Behaviour:
The syntax of pipeline operator(https://github.com/tc39/proposal-pipeline-operator/) can be compiled and recognized correctly.

Actual Behaviour:
console.dir( event.currentTarget |> CT.gPElem );
After transcoding:
![image](https://user-images.githubusercontent.com/12012671/93732185-c98fcc80-fc02-11ea-95e8-e607eacfb7ad.png)
console.dir(event.currentTarget |  > CT.gPElem);
PS:
There is an extra space between the vertical bar and the arrow!!!
This will cause the subsequent "Babel loader" to not compile the transcoding code correctly.
tsconfig.json The latest configuration is also set in:
"target": "ESNEXT",
"module": "ESNext"

Steps to Reproduce the Problem:
nothing.

Location of a Minimal Repository that Demonstrates the Issue:
nothing.

**Comment by appzuka** [comment]
I believe this is not yet implemented in TypeScript.  There is a [PR](https://github.com/microsoft/TypeScript/pull/38305) for this in TypeScript but it seems this is not yet implemented.  This could be because, as the link you provided says:

> The details of the pipeline syntax are currently unsettled.

Trying to compile this syntax in plain TypeScript with tsc fails.  ts-loader allows tsc to be used in webpack pipelines so as soon as this is implemented in tsc it will work in ts-loader. As noted [here ](https://github.com/microsoft/TypeScript/issues/17718#issuecomment-472714534) TypeScript will not implement new features until they reach stage3 and this proposal has issues, so it may not be coming soon.

**Comment by LP1994** [comment]
> I believe this is not yet implemented in TypeScript. There is a [PR](https://github.com/microsoft/TypeScript/pull/38305) for this in TypeScript but it seems this is not yet implemented. This could be because, as the link you provided says:
> 
> > The details of the pipeline syntax are currently unsettled.
> 
> Trying to compile this syntax in plain TypeScript with tsc fails. ts-loader allows tsc to be used in webpack pipelines so as soon as this is implemented in tsc it will work in ts-loader. As noted [here ](https://github.com/microsoft/TypeScript/issues/17718#issuecomment-472714534) TypeScript will not implement new features until they reach stage3 and this proposal has issues, so it may not be coming soon.

Thank you for your reply!

I hope it will become a formal syntax as soon as possible. After all, chained programming is quite convenient in some cases, and JS also needs such a convenient chained syntax.

I am a front-end developer who is keen on ES6 series syntax. I have always believed that JS is the best programming language in the galaxy. After encountering typescript, I am more convinced that JS is the best programming language in the universe.

After that, I'll turn that off. Thank you again for your reply! You are also welcome to visit China in the future.
