### ISSUE TITLE
Module parse failed: Unexpected token (9:11) You may need an appropriate loader to handle this file type

### ISSUE THREAD

**Issue by dragonDScript** [TypeStrong/ts-loader#1210]
### Expected Behaviour
Ts-Loader should convert the types to javascript
### Actual Behaviour
It fails, like if no loaders were set.
### Steps to Reproduce the Problem
Clone https://github.com/X-Store-App/client
Checkout to dev
Run npm start
See error
### Location of a Minimal Repository that Demonstrates the Issue.
https://github.com/X-Store-App/client

**Comment by appzuka** [comment]
@dragonDScript, I checkout out your repository but could not reproduce the problem.  It looks as if you are still working on this project.

If there is still a problem please confirm which commit I should be looking at and how to reproduce.

**Comment by dragonDScript** [comment]
Hey @appzuka, could you please check the terminal after few seconds? The error needs some secs to appear since Webpack is bundling "preload" and "main" before. If you can't reproduce yet, I'll try to delete and install node modules.
And thank you by helping me!

**Comment by appzuka** [comment]
@dragonDScript, I observed the error.  The problem is that in your webpack.config.js you are using ./src/main/index.ts as your entrypoint:

https://github.com/X-Store-App/client/blob/c852478ec104329be0f7519ae022c6b48c1c6169/webpack.config.js#L65

But you are only using the ts-loader to transpile the files for jsx and tsx files in the interface folder:

https://github.com/X-Store-App/client/blob/c852478ec104329be0f7519ae022c6b48c1c6169/webpack.config.js#L73

If you add the following at line 72 it compiles successfully:

```
      {
        test: /\.ts$/,
        use: 'ts-loader',
        include: path.resolve(__dirname, 'src', 'main'),
        exclude: path.resolve(__dirname, 'node_modules')
      },
```
Good luck with the app.

**Comment by dragonDScript** [comment]
Thank you. It worked! @appzuka 
It was a typo when I copied main to interface.
You are awesome!
