### ISSUE TITLE
resolveJsonModule problem

### ISSUE THREAD

**Issue by clbagrat** [TypeStrong/ts-loader#1241]
### Expected Behaviour
imported json file has to be copied to a build folder, along with d.ts files.

### Actual Behaviour
imported json file doesn't get copied to a build folder.

### Steps to Reproduce the Problem
clone https://github.com/clbagrat/ts-loader-repro
run `npm run build`
check that `/builld/config/config.json` doesn't exist.
check that `'../config/config.json';` inside `/build/src/index.d.ts` can't be resolved
 
### Steps to Reproduce expected behavoiur
clone https://github.com/clbagrat/ts-loader-repro
run `tsc`
check that `/builld/config/config.json` exists.
check that `'../config/config.json';` inside `/build/src/index.d.ts` resolved

### Location of a Minimal Repository that Demonstrates the Issue.
https://github.com/clbagrat/ts-loader-repro

thanks ;)

**Comment by johnnyreilly** [comment]
Interesting - I've had it work for my own setups. Perhaps you need to add "JSON" to your extensions in your webpack config?

**Comment by clbagrat** [comment]
Thanks for your attention, @johnnyreilly 

I've added a `.json` (and `JSON` as advised) to the extension list. 
https://github.com/clbagrat/ts-loader-repro/commit/d5371dba6f7257a833598a17fab148e63dc14f6e

Unfortunately, the problem still exists.

**Comment by appzuka** [comment]
@clbagrat,  I believe you are observing correct behaviour.  The contents of the json file will be included in the bundle but the file itself will not be copied to the output.

Consider if you included a second ts file which is imported in index.ts.  Say file.ts which exports x.  You would include this in index.ts with the statement:

```
import x from './file.ts';
```

You would expect x to be included in the final index.js bundle but you would not expect file.ts (or .js) to be included in the output folder.

If you use config in your index.ts: <code>console.log(config);</code> and then <code>npm run build</code> you will see that foo is included in index.js.

**Comment by johnnyreilly** [comment]
Yup this sounds correct - for clarification, when I suggested things work for my own setup, what I meant was I could successfully import and consume JSON from TypeScript; not necessarily copying raw JSON files.

**Comment by clbagrat** [comment]
Thanks a lot for your time, but I think there is a misunderstanding. 
I do not expect a json file to be copied to the output folder along with a built file (a bundle). 
I do expect that a json file will be copied to the output folder along with *d.ts files, so types derived from that json could be resolved. 

If only I could demonstrate a problem more visible, than in my repro repo. But I'll try anyways.

Actual output folder:

![image](https://user-images.githubusercontent.com/1269797/105552884-df261780-5d04-11eb-86e4-5151e8a70dec.png)

> Here you can see that `import config from '../config/config.json';` cannot be resolved. Note that it's the index.d.ts can't do so, not the index.js. 

---
Expected output folder, the one that I get if I use `tsc`:

![image](https://user-images.githubusercontent.com/1269797/105553281-62e00400-5d05-11eb-94b2-2dcb22b41546.png)

> Here you can see that config/config.json can be resolved, because an actual json file is copied along with other type definitions. 

---

Another remark:
@appzuka said that.

> The contents of the json file will be included in the bundle but the file itself will not be copied to the output.

In fact, it shouldn't, and it's not included, as long as I'm using it just to define a type. I'm not processing a content of this json in any other way. 
My real use case is that I'm trying to provide the best dev experience by enabling an autocomplete for ~30 icon names.
 
https://user-images.githubusercontent.com/1269797/105553892-940d0400-5d06-11eb-89f5-8ccc03f64e3b.mov

Once again, thanks a lot for your time and effort, I'm highly appreciating this.
                                                                                       (and sorry for my English)

**Comment by appzuka** [comment]
@clbagrat,

You are correct in saying that the contents of the son file will not be included in the bundle if you do not use it, which is why I said you need to use it with a statement such as <code>console.log(config)</code> in order to see it.  If you don't use it webpack is intelligent enough to drop it from the bundle.

It still seems right to me that webpack and ts-loader do not emit the json.  webpack is a bundler so you would expect it to bundle what is used and drop what is not.  Some possible solutions for your use case are:

1) Use tsc.  I assume you are generating a library which will be consumed elsewhere, so tsc might be the right tool.  The bundling will be done when the library is consumed.

2) Tell webpack you want the json file to be placed in the build folder. You can use copy-webpack-plugin or a similar plugin for this.

3) Put your autocomplete values in a .ts or .d.ts file instead of importing them from a .json file.

I can see an argument that as a .d.ts file is emitted with an imported json then the json should be included alongside the .d.ts file.  As other solutions are available I'm not sure it is worth adding this feature to ts-loader but you could submit a PR if the solutions above do not work for you.

**Comment by clbagrat** [comment]
Yep, so far I'm using a solution 2, since it's the only one that fits my needs. It just felt a bit smelly, since I have to add an addon on top in order to support a built-in feature of a language. Feels like a polyfill :) 
Anyways, thanks a lot for you time and help. I'll do my best to open a PR, but can't promise :)
