### ISSUE TITLE
using ts-loader to emitDeclerationOnly

### ISSUE THREAD

**Issue by ZNackasha** [TypeStrong/ts-loader#1269]
currently i am using bable-loader to generate the javascript from typescript. but i want to generate typescript declarations as well.

to solve this originally i simply added `tsc --emitDeclarationOnly` at the end of our build script. this approach works for building but not for watch

hence i wanted to still use the ts-loader just of emitDeclarationsOnly. however i kept getting the following error

```log
lerna ERR! yarn run build stdout:
$ cross-env NODE_ENV=production webpack --config ./webpack.config.js --mode production
assets by status 122 KiB [cached] 117 assets
./src/index.ts 39 bytes [built]

ERROR in ./src/index.ts
Module build failed (from ./node_modules/ts-loader/index.js):
Error: TypeScript emitted no output for G:\SOMEPATH\src\index.ts.
    at makeSourceMapAndFinish (G:\SOMEPATH\node_modules\ts-loader\dist\index.js:53:18)
    at successLoader (G:\SOMEPATH\node_modules\ts-loader\dist\index.js:40:5)
    at Object.loader (G:\SOMEPATH\node_modules\ts-loader\dist\index.js:23:5)

webpack 5.11.1 compiled with 1 error in 8620 ms
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

my tsconfig is

```json
{
  "compilerOptions": {
    "alwaysStrict": true,
    "declaration": true,
    "declarationMap": true,
    "esModuleInterop": true,
    "emitDeclarationOnly": true, // <------ magic
    "lib": ["ESNext", "DOM"],
    "module": "esnext",
    "moduleResolution": "node", 
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noImplicitThis": true, 
    "useDefineForClassFields": true,
    "outDir": "./dist/",
    "sourceMap": true,
    "strict": true,
    "strictFunctionTypes": true, 
    "strictNullChecks": true, 
    "strictPropertyInitialization": true, 
    "target": "es2015",
    "types": []
  },
  "exclude": ["node_modules"],
  "files": [
    "./src/index.ts",
    "./src/index.d.ts",
  ]
}
```

webpack

```js
/* eslint-disable @typescript-eslint/no-var-requires */
const path = require('path');

const isProduction = process.env.NODE_ENV === 'production';

module.exports = {
  cache: {
    type: 'filesystem',
  },
  devtool: isProduction ? 'source-map' : 'source-map',
  entry: './src/index.ts',
  module: {
    rules: [
      {
        enforce: 'pre',
        exclude: /node_modules/,
        test: /\.(ts|tsx)$/,
        use: [
          {
            loader: require.resolve('eslint-loader'),
            options: {
              eslintPath: require.resolve('eslint'),
            },
          },
        ],
      },
      {
        exclude: /node_modules/,
        use: ['ts-loader'],
      },
      {
        exclude: /node_modules/,
        test: /\.tsx?$/,
        use: ['babel-loader'],
      },
    ],
  },
  output: {
    filename: 'index.js',
    globalObject: 'this',
    library: 'data',
    libraryTarget: 'umd',
    path: path.resolve(__dirname, 'dist'),
  },
  resolve: {
    extensions: ['.tsx', '.ts', '.js'],
  },
};
```

**Comment by appzuka** [comment]
webpack is complaining that ts-loader returned no output when it was expecting ts-loader to return transpiled javascript.  But that was to be expected because you have used emitDeclarationOnly.

I'm not sure what happens when you specify multiple loaders for the same file type like this.  Does webpack only use the last loader specified? If it does, you could just drop the emitDeclarationOnly and webpack will ignore the output.  Otherwise, you could probably run tsc with a custom plugin.

**Comment by ZNackasha** [comment]
@appzuka no it actually uses all the loaders from bottom up or left to right.

**Comment by appzuka** [comment]
I understand that if you have multiple loaders in the <code>use</code> property of a rule then the loaders are chained right to left or bottom up.  Your configuration is different.  You have multiple rules that are triggered by *.tsx files and one rule with no test at all.  In this case I'm not sure what webpack does or even if this is a valid configuration.

If webpack uses all the loaders bottom to top then this is not going to work anyway.  A tsx file would be processed to JavaScript by the bottom loader (babel-loader) but then the next loader (ts-loader) would receive JavaScript, not TypeScript.

But I'm really not sure processing the same file with multiple rules is a valid configuration anyway.  It looks as if multi-loader was written for this case https://v4.webpack.js.org/loaders/multi-loader/.  I have never used multi-loader and don't know whether it still works for webpack 5.

I assume you have a reason for using babel-loader to generate JavaScript instead of TypeScript.

**Comment by melloc01** [comment]
I'm still having issues even using multi-loader, doesn't seem to solve the problem since it is actually webpack expecting an output, not the babel-loader.

**Comment by melloc01** [comment]
This is the culprit line: https://github.com/TypeStrong/ts-loader/blob/0d6c803a4c8d4491e6a81b6375a6fb2b526bf74e/src/index.ts#L94

**Comment by appzuka** [comment]
@melloc01 , are you seeing the same error as @ZNackasha reported? (Error: TypeScript emitted no output for G:\SOMEPATH\src\index.ts.)  The error is coming from webpack.  It is reporting that ts-loader emitted no output, which is not surprising as @ZNackasha told it not to produce any output.

This seems a strange use case as it runs ts-loader but then tells it not to produce any Javascript output. I'm also not sure that the webpack config given above is valid.  Perhaps you could explain what you expect ts-loader to do in this case and provide a minimal repository demonstrating the issue.

**Comment by thorsent** [comment]
Workaround posted here: https://stackoverflow.com/questions/66589942/using-ts-loader-to-run-emitdeclarationonly/70994678#70994678

**Comment by xiaolin99** [comment]
the only workaround I found is to run tsc manually e.g. in package.json:
```
"scripts": {
    "build": "tsc && webpack",
  },
```
then `npm run build` to build

**Comment by petatemarvin26** [comment]
I guess `ts-loader` designed to emit javascript bundle, if your goal is to `--emitDeclarationOnly` use `tsc` instead, and if you are trying to use ts-loader just to mimic the error of typescript so for sure you are going to use `--noEmit` but ts-loader will still gives you an exception `TypeScript emitted no output for /file/has/error` in that case you might want to use hook like `fork-ts-checker-webpack-plugin` 

> the only workaround I found is to run tsc manually e.g. in package.json:
> 
> ```
> "scripts": {
>     "build": "tsc && webpack",
>   },
> ```
> 
> then `npm run build` to build

This is good though, but you wish to check the type first before emittting the declaration file `"build": "webpack && tsc"`
