### ISSUE TITLE
custom loader in chain with ts-loader consumes ts files

### ISSUE THREAD

**Issue by roman0x58** [TypeStrong/ts-loader#1271]
### Expected Behaviour
Custom loader chained with ts-loader handles files that matches by webpack rule `test` configuration property
### Actual Behaviour
Custom loader gets contents from `.ts` files, that doesn't match by webpack rule `test` configuration property
### Steps to Reproduce the Problem
1. clone https://github.com/roman0x58/webpack-chaining-issue
2. npm install
3. npm run dev
4. Trigger the change of `index.ts` file
5. Custom loader prints contents from`.ts` files, but actually the loader should work only with `.gql` files
### Location of a Minimal Repository that Demonstrates the Issue.
https://github.com/roman0x58/webpack-chaining-issue

btw I'm not sure that is webpack or ts-loader issue.

**Comment by appzuka** [comment]
I took a look at your repo and observed the same as you. I observed that if you include the transpileOnly option for ts-loader the problem goes away:

```
      {
          loader: 'ts-loader',
          options: {
              transpileOnly: true,
          }
      },
```

You may not be able to use transpileOnly but if I assume your loader converts the gql file to TypeScript then you may be OK for ts-loader to transpile the output to JavaScript without referencing the other files in the project.  I don't think you need the <code>appendTsSuffixTo</code> either, at least not for simple cases.

I don't fully understand why this is happening.  Perhaps if you don't include transpileOnly then ts-loader checks all ts files in scope, although it is surprising that it processes them through the loader.  This issue discusses problems chaining loaders with transpileOnly as a solution: https://github.com/TypeStrong/ts-loader/issues/223#issuecomment-737351678. Hopefully transpileOnly will solve your issue here.

**Comment by roman0x58** [comment]
@appzuka yep, probably this is solution, but I would like to generate declaration files automatically, and when I was dealing with it, I found that `ts-loader` with `transpileOnly` can't do this
