### ISSUE TITLE
How to include files that are not explictely required or imported?

### ISSUE THREAD

**Issue by oliverjanik** [TypeStrong/ts-loader#130]
I have a ts project that utilizes internal modules with this tsconfig:

```json
{
    "compilerOptions": {
        "target": "es5",
        "sourceMap": true,
        "module": "commonjs",
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true
    },
     "exclude": [
         "node_modules",
         "bower_components"
     ]
}
```

When I use tsc it correctly compiles every ts file and excludes node_modules and bower_components. 
However ts-loader only compiles single file that is specified in webpack.config.js as an entry point.

Do I really have to import every file in all the dirs to be included in the bundle?

**Comment by jbrantly** [comment]
The concept of internal modules/namespaces isn't really supported in webpack. Instead you should be using CommonJS modules. Each module explicitly `requires` its dependencies, and from that webpack can build a dependency graph to bundle. Since you're using an internal module, there is no `require` statement and webpack only bundles the entrypoint since it doesn't believe there are any dependencies.

**Comment by oliverjanik** [comment]
If there's now way around it I'll just have to do a sweeping refactoring, then.

**Comment by jbrantly** [comment]
Using real modules (either CommonJS or ES6) is really the way to go. Internal modules/namespaces is a legacy method of web development and only supported in TypeScript for backward compatibility. Good luck!
