### ISSUE TITLE
"Debug Failure. False expression." after each change with ts-loader and webpack-dev-server

### ISSUE THREAD

**Issue by 0x53A** [TypeStrong/ts-loader#1386]
please see https://github.com/microsoft/TypeScript/issues/46555

I have a setup with webpack, ts-loader and typescript where after a single change typescript errors out and I have to restart WDS.

### Reproduction

```
cd apps\app1\app
yarn
yarn start
```

meanwhile, open file [``apps\app1\client-components\src\lib.ts``](https://github.com/0x53A/typescript-46555/blob/master/apps/app1/client-components/src/lib.ts) and change the returned number

### Location of a Minimal Repository that Demonstrates the Issue.

https://github.com/0x53A/typescript-46555

**Comment by appzuka** [comment]
@0x53A,

I have not investigated your code fully but I think you are trying to use TypeScript project references. When you are using project references TypeScript will pre-transpile your references and you should be including the transpiled code in your main app.  So in App.tsx where you have:

```
import {f} from 'client-components/src/lib';
```

You should be importing from the transpiled JavaScript, not the source TypeScript.

I wrote a couple of Medium articles on ts-loader and project references that you might find helpful:

https://medium.com/@nickexcell/using-typescript-project-references-with-ts-loader-and-webpack-part-1-5d0c3cd7c603

**Comment by 0x53A** [comment]
Hi @appzuka, thank you for taking a look and for writing the articles!

Are you a 100% sure about

> You should be importing from the transpiled JavaScript, not the source TypeScript.

?

The [documentation](https://www.typescriptlang.org/docs/handbook/project-references.html#what-is-a-project-reference) is a bit vague, but it says

> When you reference a project, new things happen:
>  * Importing modules from a referenced project will instead load its output declaration file (.d.ts)

and most other tutorials about project references also continue to just reference the source code.

--------

The issue with referencing the transpiled output is that tsc does not copy any asset files (css, images, etc) so if you import them from next to your source files, they will be missing.

**Comment by appzuka** [comment]
Hi @0x53A,

There are a lot of examples and tutorials on project references which, I believe, are incorrect.  Last year I spent some time understanding project references in TypeScript and ts-loader and I wrote the medium articles and ts-loader documentation.  I may not be 100% correct but I feel comfortable with my understanding.

In TypeScript, project references are a way to split up a project.  In build mode tsc will pretranspile the references before the main project. If one of the source files in a referenced project changes tsc will automatically rebuild it otherwise it will just use the transpiled code.  If you import the sub-project's source code then there is no point using project references - just use a library or sub-folder with your sub-project.  Then you will miss out on the speed advantage of using project references.

The reason a d.ts file is loaded when you import a referenced project is that you are importing the plain JavaScript so you need the declaration file to do the typechecking.  If you import the source TypeScript you would not need the declaration file.

Project references is a feature of TypeScript, which does not know about asset files such as css or images.  If you need these you need to arrange for them to be copied as part of your build process.  Otherwise, just split your sub-project into a sub-folder of your main project.  You can  also package your sub-project as an npm package, although you will lose the benefit of sub-projects automatically being re-compiled if you make changes in them.

**Comment by adipascu** [comment]
I am still having this issue, I think we should reopen.
