### ISSUE TITLE
Multiple instances of Three.js being imported when building with ts-loader

### ISSUE THREAD

**Issue by sidsethupathi** [TypeStrong/ts-loader#1409]
I recently upgrade my `three` and `three-stdlib` dependency versions in a project, and noticed a new warning being logged to the console complaining that multiple instances of Three.js were being imported in the produced bundle. After some investigation, it looks like it only happens when `ts-loader` is involved. The minimal repro repo uses the same source code for `vanilla.js` and `typescript.ts`.

### Expected Behaviour
A single instance of Three.js is imported, like what happens with the vanilla javascript build in the minimal repro repo.

### Actual Behaviour
Multiple instances of Three.js are imported in the produced build.

### Steps to Reproduce the Problem
In the minimal repro repo, `yarn install` and then `yarn start`. Then open `/public/vanilla.html` and `/public/typescript.html` and compare the console logs.

### Location of a Minimal Repository that Demonstrates the Issue.
https://github.com/sidsethupathi/three-ts-loader-repro/tree/28837a195b23935a0c4dda170c1f872da45200e8

**Comment by sidsethupathi** [comment]
After running `git bisect`, it looks like this commit https://github.com/mrdoob/three.js/commit/1c685e6eb56e54c4609b7b3af764e2e5110abfbf from https://github.com/mrdoob/three.js/pull/23315 is where this issue started with the minimal repo, if that points to any clues.

**Comment by johnnyreilly** [comment]
Fascinating and baffling!

**Comment by Hedgestock** [comment]
Same issue here, do we have an update on that ?

**Comment by lukehorvat** [comment]
Yes, I encountered this issue recently too, due to the following code:

```ts
import * as THREE from 'three';
import { FlyControls } from 'three/examples/jsm/controls/FlyControls.js';
```
It seems that importing Three.js + addons like`FlyControls` causes both the CJS and ESM instances of Three.js to end up in the bundle:

<img width="400" src="https://github.com/TypeStrong/ts-loader/assets/1034878/5a18114c-d30d-45cb-a3c2-c694aed25675">

I fixed it by updating my `tsconfig.json` like so:

```diff
 {
   "compilerOptions": {
     "target": "ES2015",
-    "module": "CommonJS",
-    "moduleResolution": "Node",
+    "module": "ES2015",
+    "moduleResolution": "Bundler",
     "esModuleInterop": true,
     "strict": true,
     "noEmitOnError": true,
     "declaration": false
   },
   "include": ["src"]
 }
```

Now only the ESM instance of Three.js gets bundled:

<img width="400" src="https://github.com/TypeStrong/ts-loader/assets/1034878/d88ea1b8-e4a7-4561-b5f9-c7e0112db86b">
