### ISSUE TITLE
Questions about sourcemap

### ISSUE THREAD

**Issue by imtaotao** [TypeStrong/ts-loader#1457]
Why is the upstream sourcemap not processed in the loader?
 > https://github.com/TypeStrong/ts-loader/blob/main/src/index.ts#L34

```js
function loader(this: webpack.LoaderContext<LoaderOptions>, contents: string, map?: Sourcemap) {
    if (map) {
       ...
    }
}
```

**Comment by johnnyreilly** [comment]
What processing did you have in mind?

**Comment by imtaotao** [comment]
I have a loader that processes source files, and then passes the `source code` and `sourcemap` to `ts-loader`, but `ts-loader` doesn't seem to merge the sourcemap passed from upstream loader.

**Comment by johnnyreilly** [comment]
What problems does that cause?

**Comment by chipzhang** [comment]
> https://github.com/TypeStrong/ts-loader/blob/9533b2dc992392623e04645b1972332bddef0c76/src/index.ts#L34

ts-loader force discards source maps generated by previous loaders

**Comment by Ka0o0** [comment]
@johnnyreilly  for us specifically this causes that we are not able to debug Vue SFC TypeScript files. This is because the ts-loader is the second loader after the vue-loader and should respect the input source maps generated by the vue-loader.

I've seen that there has already been made a suggestion on how to handle this: https://github.com/TypeStrong/ts-loader/pull/1367 . I've tested the changes in one of our Vue projects and debugging works with those changes.
