### ISSUE TITLE
No Output using TypeScript 1.8.0 Beta

### ISSUE THREAD

**Issue by MikeRyan52** [TypeStrong/ts-loader#147]
Using the TypeScript 1.8.0 compiler I'm getting the following error:

```
ERROR in ./app/bootstrap.ts
Module build failed: Error: Typescript emitted no output for /demo-project/app/bootstrap.ts
    at Object.loader (/demo-project/node_modules/ts-loader/index.js:421:15)
```

I tried tracking it down and it seems like the `name` property for `outputFiles` has changed, but I couldn't find a corresponding breaking change for the TS compiler that would cause that to be the case.

**Comment by jbrantly** [comment]
I'm unable to reproduce this, and according to the tests [here](https://travis-ci.org/TypeStrong/ts-loader/jobs/105594234) the test suite runs fine on TS 1.8.

Assuming things work fine with TS 1.7.5 but fail with TS 1.8, my guess is that there was a change where your bootstrap.ts now causes TypeScript to not emit output for whatever reason. It would be interesting to run `tsc` against it and see what happens. 

This is likely related to #91, meaning, if something in your file caused TypeScript to fail currently ts-loader isn't reporting what the issue is so it makes it hard to investigate/fix.

**Comment by MikeRyan52** [comment]
Ah, I was led me to believe it might be something to do with ts-loader as running `tsc` against the project works fine with TypeScript 1.8 .

Thanks for running the tests against 1.8! Verifies the problem is on my end somewhere.

**Comment by jbrantly** [comment]
Definitely reopen if you feel like it might be a problem with ts-loader and we can try to figure it out.

**Comment by stepancar** [comment]
@jbrantly i have the same issue, after removing noEmit: true from tsconfig - it works fine

**Comment by kaw2k** [comment]
Same here, removing `noEmit: true` it works

**Comment by adamlewy** [comment]
removing `noEmit: true` is not a solution, we need it disabled in our flow but then we can't upgrade our Typescript version to 1.8

**Comment by stepancar** [comment]
@adamlewy [see this comment ](https://github.com/TypeStrong/ts-loader/pull/157#issuecomment-186229913) works for me

**Comment by adamlewy** [comment]
@stepancar overwriting `"noEmit": false` inside webpack config worked, thanks!
