### ISSUE TITLE
Definition files generation with semi absolute path inside of build directory

### ISSUE THREAD

**Issue by mrblackus** [TypeStrong/ts-loader#186]
Since version 0.8.2, all `d.ts` files are now generated with full absolute path _inside_ build directory (the one set on webpack configuration).

For example, considering I have  `outDir` set to `ts-build` on `tsconfig.json`, I have:

```
.
├── Users
│   └── mrblackus
│       └── Projects
│           └── js
│               └── fooProject
│                   └── build
│                       └── ts-build
│                           └── foo.d.ts
├── foo.js
└── foo.js.map
```

Instead of 

```
.
├── foo.js
├── foo.js.map
└── ts-build
    └── foo.d.ts
```

This issue is initially reported by @Bartzy and myself on https://github.com/TypeStrong/ts-loader/pull/175.

**Comment by Bartzy** [comment]
Any progress on this?

It makes emitting typings with webpack pointless since the paths are all wrong.

Thanks!

**Comment by 17cupsofcoffee** [comment]
It's relating to a different issue, but I think there's a decent chance the pull request (#214) I submitted might fix this - although at the minute the file paths are based on the current working directory, rather than being relative to the entry point, which I don't think is quite right. It's a start, though.

**Comment by Bartzy** [comment]
@jbrantly Can you comment about this issue? Thanks!
