### ISSUE TITLE
Map files for vue files holding ts scripts

### ISSUE THREAD

**Issue by druppy** [TypeStrong/ts-loader#398]
Hi ...

I have with success setup webpack using ts-loader, and using VueJS vue files that holds inline ts code. Besides some lake og IDE completion support for the nice format, it all build and works as expected.

But ... the map files for these files does not work, plain ts files works, ts files included via ```<script src="my_file.ts"> ...``` works too, but if the ts code is inline in the vue files, it compiles fine and works, but the map files are broken.

Are there anything that need special attention for mapfiles to work in vue files compiled via ```ts-loader``` ?

I am using the new option

```javascript
ts: {
        appendTsSuffixTo: [/\.vue$/]
}
```

**Comment by johnnyreilly** [comment]
@herringtondarkholme any thoughts?

**Comment by HerringtonDarkholme** [comment]
I don't think it is possible, for now. If I remember the implementation correct, ts-loader reuses the virtual file from vue-loader and appending new suffix to them. On one hand, vue-loader does not handle sourcemap itself but use a third party sourcemap generator. On the other hand, ts-loader's sourcemap is powered by TypeScript compiler, which is out of control of ts-loader.

The problem is probably third party generator is not compatible with ts-loader or so. I'm not 100% sure, but I have experimented earlier but failed to solve this problem.

**Comment by druppy** [comment]
Thanks for the explanation, that makes sense. This explains why I have map files for css/stylus but not typescript.  

It sound like this will not be solved before tsc becomes more stream like in nature. So use the `src` attr to use external `ts` files, if you need debugging.

Anyway, thanks for all your nice work on this ts-loader !

**Comment by roryprimrose** [comment]
I've got this to work. See [https://github.com/HerringtonDarkholme/vue-ts-loader/issues/3](https://github.com/HerringtonDarkholme/vue-ts-loader/issues/3)

The only issue is that you have to roll this pattern to all vue files otherwise it will not work.

**Comment by roryprimrose** [comment]
Ah, sorry, I misunderstood this issue. I haven't check whether map files work, but I did get external files working.
