### ISSUE TITLE
[Qu ]Devtool webpack option vs sourcemap tsconfig options

### ISSUE THREAD

**Issue by QuantumInformation** [TypeStrong/ts-loader#435]
What is the interaction between the Devtool webpack option vs sourcemap tsconfig options? Does one override/overlap the other?

**Comment by johnnyreilly** [comment]
As I understand, sourcemaps generated by TypeScript are passed onto webpack. You need both if you want to debug original source.

**Comment by QuantumInformation** [comment]
Thx, as an experiment I removed the source map option from the tsconfig:

```
{
  "compilerOptions": {
    "target": "es5"
  },
  "include": ["./src/**/*.ts"],
  "alwaysStrict": true,
  "types": [
    "node"
  ]

}
```
and still got the source maps output when doing: `  devtool: "source-map",
`

**Comment by bbottema** [comment]
I still don't understand the difference. 

I suppose the typescript compiler can generate maps so that what the option in tsconfig would be for. But something like Webpack's awesome-typescript-loader might use this option too? Any overlap then? 

What if sourcemap is enable in the UglifyPlugin? How do devtool and tsconfig sourcemap flags figure in here?

**Comment by johnnyreilly** [comment]
> Webpack's awesome-typescript-loader might use this option too? Any overlap then?

I believe atl sets sourcemaps to true in tsconfig.json if it's enabled in webpack.  Ts-loader generally opts to be a drop in replacement for tsc in​terms of behaviour and so does not change compiler settings - you have to do it manually.

> What if sourcemap is enable in the UglifyPlugin? How do devtool and tsconfig sourcemap flags figure in here?

Honestly I've never tried it - sorry
