### ISSUE TITLE
why not define the typescript dependency in package .json?

### ISSUE THREAD

**Issue by zzzgit** [TypeStrong/ts-loader#458]
why not write a typescript dependency in the package.json?

**Comment by johnnyreilly** [comment]
We do

**Comment by jbrantly** [comment]
To clarify, it's in package.json as a dev dependency since it's used to compile the source of the loader. It's not a normal dependency because the loader supports multiple versions of TypeScript and it's up to the user to install the appropriate version of TypeScript for their use case.

Basically if we installed it as a regular dependency then users would be locked in to whatever version ts-loader specified.

**Comment by johnnyreilly** [comment]
What he said
