### ISSUE TITLE
whitespaces eating in markup 

### ISSUE THREAD

**Issue by stepancar** [TypeStrong/ts-loader#49]
@jbrantly Hello!
in rendered markup i haven't whitespaces which was in source code.
its reason why my styles crashed. is this propblem of loader or maybe with react?
Thank you!

**Comment by jbrantly** [comment]
I assume you mean you're using JSX? Assuming so, I doubt it's an issue with the loader. You should be using either TypeScript or Babel to transpile your JSX (based on the `jsx` TypeScript option). If you're using TypeScript, I would first check to see if the same JSX outputs the same way in Babel. If it's different it might be a bug in TypeScript which you should report to them. If it's the same it's probably just a JSX whitespace handling rule (which I'm not familiar with off the top of my head).

I would suggest creating a simple TypeScript file and just using `tsc` to compile it to remove everything else from the equation.

**Comment by basarat** [comment]
> in rendered markup i haven't whitespaces which was in source code.

Try opening the file in atom-typescript and see what js that (and basically ntypescript) generates. If you disagree with that then validate that its *inconsistent* with the official (https://babeljs.io/repl/). If so then raise a bug with Microsoft/TypeScript and link back for our knowledge :rose:

**Comment by basarat** [comment]
If ntypescript (ie. typescript latest) is inconsistent with what ts-loader is generating we can discuss further

**Comment by stepancar** [comment]
@jbrantly , @basarat thank you for your answers.
Yes, it's not trable of loader ot typescript.
React generates dom elements without padding between tags
```xml
<ul><li></li></li></li><ul>
```
 etc,
Usually we have 
```xml
<ul>
    <li></li>
    </li></li>
<ul>
```
in ie<10 for justify divs we use css text-align:justify (!!!)
in rendered markup by rect we haven't whitespaces between tags and styles crashs.
in ie10+ we can use flexbox.

**Comment by basarat** [comment]
@stepancar for : 

```
<ul>
    <li></li>
    <li></li>
</ul>
```

The outcome for *jsx* is : 

`<ul><li></li><li></li></ul>`  [sample](https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=%3Cul%3E%3Cli%3E%3C%2Fli%3E%3Cli%3E%3C%2Fli%3E%3C%2Ful%3E)

I have just checked and the `tsx` output *is the same*. 


So no bug in *TypeScript*. This is just how *jsx* is designed to work. 

Note: JSX is *not the same as html*. If you want spaces you can always do `{' '}` or write in a single line   `<ul>          <li></li><li></li></ul>`. Its designed for convenience rather than html parity (not my choice!).

Sorry I'm a bit confused about what the question is but hopefully I've answered it :rose:
