### ISSUE TITLE
Support compile to ts languages -- respect webpack config for ts files

### ISSUE THREAD

**Issue by RussellSprouts** [TypeStrong/ts-loader#506]
I'm trying to use a loader to augment my existing ts files with extra data, so that we can leverage the typechecking features. In the webpack config, I have something like this:

```
{ test: /\.ts$/, loader: 'ts!extra-data' }
```

The Typescript files are otherwise normal, but the `extra-data` loader puts in additional lines (a representation of a template for compile time validation).
The ts-loader doesn't always apply the extra-data loader, however.

If I import a file like this:
```
import "src/needs-extra";
```
Then ts-loader will apply the extra-data loader and import the file with extra data.

But if I import it like this:
```
import data from "src/needs-extra";
```
Then ts-loader will skip the extra-data loader and interpret it directly as TypeScript. I would expect that all files imported use the loaders specified in the webpack config.

**Comment by johnnyreilly** [comment]
I'm afraid I've no experience of using ts-loader like this. We're open to PRs though

**Comment by grantila** [comment]
The problem is actually pretty severe if you look at it from a philosophical point of view. `ts-loader` goes against webpack's idea of loaders.

Basically, webpack should handle reading files from the disk. It then passes the content through a chain of loaders to modify this file in certain ways. `ts-loader` breaks this by following the `import`s, and reading these imported files manually (`fs.readFileSync` in `src/instances.ts`). This means that it's impossible to build loaders that go before `ts-loader` (e.g. things that transpile *to* TypeScript, or loaders that append/prepend/modify the file content). This can be very useful and is the whole point of webpack and its concept of loaders.

What you can probably do @RussellSprouts is to use `const foo = require('foo')` rather than `import foo from 'foo'` which will bypass TypeScript's/`ts-loader`'s auto-load/auto-readfile logic, and allow webpack to manage this module dependency. That will allow your custom loaders to successfully parse your file and provide the _parsed_ data to the final ES6-module (given you're using webpack's module support).

I'm in the same situation, having written `pure-jsx`, which allows you to separate pure view code from _logic_ by supporting files which are complete html/xml/jsx syntax, without any code wrapping it. My logic won't work with the regular `import`'s either.

I'm not familiar with how webpack implements and manages loaders in terms of sub dependencies, but I'd love to see TypeScript and this loader to support being augmented and wrapped. For this, TypeScript's own concept of modules must be dropped in favor of allowing systems _on top of_ TypeScript to perform wrapping, by making it possible to intercept the module loading. Currently, TypeScript (and `ts-loader`) stands out as not following the ideas of webpack loaders...

**Comment by johnnyreilly** [comment]
I haven't been tracking this issue particularly but I did wonder if the same issues apply when using ts-loader in `transpileOnly` mode? Also, would this PR help your use case? https://github.com/TypeStrong/ts-loader/pull/520
