### ISSUE TITLE
TypeScript 2.3 checkJs support

### ISSUE THREAD

**Issue by OliverJAsh** [TypeStrong/ts-loader#518]
I am trying to use the new `checkJs` flag in TypeScript 2.3. When I run `tsc` standalone, I get errors from my JS files, however when I run `ts-loader`, I get no errors from my JS files.

Any idea what might be causing this?

**Comment by johnnyreilly** [comment]
Are you using TypeScript 2.3 in your package.json?

**Comment by OliverJAsh** [comment]
I am. I checked with `yarn list typescript` and only 2.3 comes up, so there's definitely not multiple versions of TS.

**Comment by OliverJAsh** [comment]
I created a small test case: https://github.com/OliverJAsh/webpack-ts-check-js/commit/c2a5d4edf7bd909c2e3ae1c49daf1c9194981bfa

In this example, the entry file is JS, which depends on a TS file. Transpilation works, but I'm expecting to see typecheck errors (`checkJs`) and there are none.

I also tried changing the entry file to TS, depending on a JS file. However that also failed to show any typecheck errors.

**Comment by schmuli** [comment]
After looking through the source code, and debugging the loader as well, I think I have identified the what can be changed to better support JS errors in `checkJs` mode:

https://github.com/TypeStrong/ts-loader/blob/master/src/after-compile.ts#L129:

Instead of filtering for only `[.d.ts, .ts, .tsx]`, use `instance.compilerOptions.checkJs` to determine the correct filter to use, similar to how `scriptRegex` is calculated in https://github.com/TypeStrong/ts-loader/blob/master/src/instances.ts#L97.

**Comment by johnnyreilly** [comment]
@schmuli  - sounds promising!  We welcome PRs 👍 😄
