### ISSUE TITLE
Deprecate `ts` option

### ISSUE THREAD

**Issue by blakeembrey** [TypeStrong/ts-loader#63]
Requires investigation, but it'd be cool to deprecate the `ts` option and recommend the `query` object for loaders.

**Comment by jbrantly** [comment]
Part of the initial reason for this was for the tests, because queries passed in using an aliased loader did not work. Unfortunately that still seems to be the case even when using the `query` object, so for the test harness the `ts` option is still useful.

However, we could still be proactive with the documentation.
