### ISSUE TITLE
Can we remove the newline logic and use the compiler options properly?

### ISSUE THREAD

**Issue by blakeembrey** [TypeStrong/ts-loader#64]
https://github.com/TypeStrong/ts-loader/blob/master/index.ts#L256-L259

**Comment by basarat** [comment]
> use the compiler options properly?

you mean that if `compilerOptions` are passed to `createProgram` [here](https://github.com/TypeStrong/ts-loader/blob/b6c18e281e5ae957b95df6f47ba0d353a38d0acf/index.ts#L232-L235) then the output received from the program should already contain the correct line endings in the output js

**Comment by jbrantly** [comment]
I just looked and it would seem that we still need to manually parse the newLine setting from the options and use `getNewLine` as we are doing today.

See https://github.com/Microsoft/TypeScript/blob/master/src/services/services.ts#L2636

When the language service creates the compilerHost it will either use the `getNewLine` from the language service host or default to CRLF. It never parses from the compiler options.

The line you linked @basarat is slightly different since we never create a language service for transpiling.
