### ISSUE TITLE
Errors from conflicts in type declarations are not being logged

### ISSUE THREAD

**Issue by martijnthe** [TypeStrong/ts-loader#683]
### Expected Behaviour

When there are conflicts in type declarations, the webpack build should be failed and the errors should be logged.

### Actual Behaviour

When there are conflicts in type declarations, the webpack build does not fail and the errors are not logged.

### Steps to Reproduce the Problem

See commit message of the commit below.

### Location of a Minimal Repository that Demonstrates the Issue.

I've created a minimal repo as an integration test case here (no fix yet though):
https://github.com/martijnthe/ts-loader/commit/b0261db63a32f497b86938e9749be507671bdcc8

Maybe same issue as / related to https://github.com/TypeStrong/ts-loader/issues/659 ?

**Comment by martijnthe** [comment]
I'm happy to take a stab at fixing this. Any pointers @johnnyreilly ?

**Comment by johnnyreilly** [comment]
Hey @martijnthe,

Historically I believe this was dealt with by using the https://www.npmjs.com/package/webpack-fail-plugin

Supposedly it's not necessary with webpack 2+

That said, the https://webpack.js.org/api/cli/#advanced-options list `bail` as an option.  You'd think I'd know for sure the distinction but actually I don't.

I'd start with researching exactly what the webpack behaviour with v2+ is supposed to be.  Could be also worth checking that the build fails if you add the webpack-fail-plugin into the mix. 

I'm initially wondering if this is a config issue instead of a code issue...

**Comment by martijnthe** [comment]
hi @johnnyreilly, thanks for your comments.

I just quickly tried out `--bail` and also the `webpack-fail-plugin`.
It does not catch the error either. FWIW, I tried with the latest webpack, v3.8.1.

> I'm initially wondering if this is a config issue instead of a code issue...

I don't think it is. Why would it matter? Are you suggesting that config issues aren't caught either?

I'll dig into the code to figure out what's going on.
