### ISSUE TITLE
Better stacktrace when an error occurs

### ISSUE THREAD

**Issue by smac89** [TypeStrong/ts-loader#809]
### Expected Behaviour
I expect a stack trace of the error and where it occured

### Actual Behaviour
I simply get a single line describing which line the error occured at

```
/home/user/WebstormProjects/vueproject/src/components/hello/Hello.vue.ts
  0:0  error  [tsl] ERROR in
              /home/user/WebstormProjects/vueproject/src/components/hello/Hello.vue.ts(21,38)

✖ 1 problem (1 error, 0 warnings)
```
### Steps to Reproduce the Problem
Start a vue-typescript project with webpack and include a rule like this:

```
{
  test: /\.tsx?$/,
  loader: 'ts-loader',
  exclude: /node_modules/,
  options: {
    appendTsSuffixTo: [/\.vue$/],
    logInfoToStdOut: true
  }
},
```

I also have the following in my webpack config:
`stats: "verbose",`

---

I have searched through all the options and I don't see anywhere that allows us to turn on printing a full stack trace of errors. I don't know if this a problem with webpack or tsloader, but I would appreciate a nudge in the right direction.

**Comment by donaldpipowitch** [comment]
Looks like you use `webpack-command`, right? The error is shown if you use `webpack-cli`, but `ts-loader` could change the error handling so the error is shown in both cases. Here is some background: https://github.com/webpack-contrib/webpack-stylish/issues/21.

**Comment by johnnyreilly** [comment]
Ah - thanks for making sense of the confusion @donaldpipowitch; good work!

I'm still rolling with `webpack-cli` which is why this hasn't bitten me yet I guess. (Might well switch at some point, but whilst `webpack-cli` "just works" I haven't felt the need.)

Either way, we'd be totally open to PRs that make ts-loader work better with `webpack-command`. The idea is we build something that serves the whole community. 

So PR at me people! :smile:

**Comment by shellscape** [comment]
Essentially: no loader or plugin should ever add plain strings to the `errors` or `warnings` collections on a compilation. Allowing strings was a glaring architectural failure leftover from the early days of webpack, and it has yet to be corrected.  Since there's really been no standard implementation nor recommendation for how loaders and plugins should be written, the ecosystem is a bit of a mess in that regard, with every author going the way they deem best for the user.

Instead, loaders and plugins should add an `Error` (preferably inherited from and extended) object that prints what they want to see via `toString()` and has additional metadata added via an `Object` property like `meta` or `metadata` but that allows consumers to examine the additional information and format accordingly. The usefulness for that approach goes well beyond `webpack-command`.

**Comment by johnnyreilly** [comment]
Thanks for the info @shellscape. If someone wants to submit a PR along the lines suggested here I'll review it. 

It's possible I might get to this myself at some point but that's likely to be later rather than sooner.

Oh and anyone putting together a PR; don't worry about initially failing tests. Just start the PR and I'll collaborate with you to get to merging status.
