### ISSUE TITLE
Should ts-loader be a necessary dependency of required modules?

### ISSUE THREAD

**Issue by ayuudee** [TypeStrong/ts-loader#82]
Hello,

I'm not entirely sure if this is a ts-loader issue or a webpack issue (or, actually, if it is an issue at all). 

I have been trying to get a particular project structure working. An example of that structure [is here]( https://github.com/ayuudee/webpack-typescript-example), but I'm struggling to understand why ts-loader should be required in the projects of the required dependencies. 

In this case, you'll notice `web/entry/foo.js` depends on `module/ts/ModuleA.ts` which itself depends on `service/ts/ServiceA.ts`. If I do not include the ts-loader dependency in `module/package.json` I see the below issue.

```
ERROR in ../module/ts/ModuleA.ts
Module not found: Error: Cannot resolve module 'ts-loader' in ...
```

Are there any ideas why this might happen? Have I approached this incorrectly perhaps? What I'm really trying to do is to cleanly decouple my modules and their dependencies from the application that will ultimately compose them.

Cheers,
Andrew.

**Comment by jbrantly** [comment]
In webpack loaders are resolved relative to the resource, so since you're not putting ts-loader in a common root webpack isn't able to find it when you load resources from another folder, thus you needing to put the ts-loader in *that* folder as well. I would suggest just installing typescript and ts-loader at the root. This should also help with performance since only one instance of ts-loader (and thus TypeScript) will be initialized.

**Comment by ayuudee** [comment]
That's great. Thanks for your help!
