### ISSUE TITLE
Multiple Typescript instances

### ISSUE THREAD

**Issue by MichaReiser** [TypeStrong/ts-loader#90]
Hy

I'm facing the issue that ts-loader uses different typescript instances to compile the files. 

How can I be sure that there are multiple instance?
ts-loader logs two messages "Using Typescript 1.6.2 with ....tslint.config

Setup
We have a plain typescript library that is packed as a node module (no compiled js, only ts). The library is included in a web project. Both projects use webpack (the library only for unit testing). 

Problems with multiple instances
ts-loader emits in this case errors from the first typescript instance. I had to remove the typescript folder from the library to be able to see the errors of the web project.

Can you create a sample project:
I failed to create a simple project that can be used to reproduce the problem. My first thought was that ts-loader creates a new instance each time it sees a tsconfig, but that's not the case. 

To figure out what the issue is, it might help to know when ts loader creates new typescript instances. I can then try to create a sample project and hopefully I succeed ;)

Thanks a lot
Micha

**Comment by basarat** [comment]
@DatenMetzgerX you can use the `compiler` option : https://github.com/TypeStrong/ts-loader#compiler-string-defaulttypescript to specify a custom compiler build

**Comment by DatenMetzgerX** [comment]
Thanks basarat

I don't want to use a special compiler instance. The problem I'm facing is, that ts-loader uses multiple instances but I don't know why... And I just want to use a single instance...

**Comment by jbrantly** [comment]
I think this might be the same as #82

> To figure out what the issue is, it might help to know when ts loader creates new typescript instances.

1. Using the `instance` option
2. Different compiler instances when using webpack's Node API

However, my guess here is that ts-loader isn't creating new typescript instances but that webpack is creating new ts-loader instances. Webpack resolves loaders relative to the resource, so when a file in the library project is being processed by webpack it's going to pick up on the ts-loader installed there and not the one in the application. Maybe installing ts-loader only as a `devDependency` in the library would resolve the issue since you're only using it for unit tests there?

**Comment by DatenMetzgerX** [comment]
I think I have figured out the issue. I link the second project into the main project. Now both projects have a node_modules folder containing the ts-loader. In this case, webpack uses two different ts-loader instances, one for each project. This breaks your instance caching as it is scoped to the file and not to the webpack execution or the compiler instance...

Might it be possible to cache the instances in the webpack compiler?

**Comment by jbrantly** [comment]
> Might it be possible to cache the instances in the webpack compiler?

That is an interesting thought. Probably. Since this is the second time it's come up it might be a good idea to try and proactively "fix", but there are still dangers (like the ts-loader versions between the two projects being out of sync and causing issues).

In the meantime I believe you can work around by using some fancy webpack config:

http://webpack.github.io/docs/configuration.html#resolveloader

```javascript
resolveLoader: {
  modulesDirectories: ["exact/path/to/app/node_modules", "web_loaders", "web_modules", "node_loaders", "node_modules"]
}
```

**Comment by DatenMetzgerX** [comment]
Different typescript versions might be a problem. Here is the question how typescript libraries should be defined (that will not compile to js first). 

A workaround is to remove the ts-loader from the node_modules directory in the library project, what is kind of annoying. 

Maybe I try to do something that is not intended to be done with typescript. Maybe we should not be using webpack in the library... as it is only used for the unit test execution (not for bundling)

**Comment by jbrantly** [comment]
> A workaround is to remove the ts-loader from the node_modules directory in the library project, what is kind of annoying.

That's not really a workaround. That is the normal solution. You would make it a dev dependency (like I mentioned before) and if you, say, publish to npm and then use that lib in some other project then ts-loader wouldn't come into play.

The issue here is that you're not publishing to npm, you're just linking to it so the dev dependency concept doesn't work.

**Comment by jbrantly** [comment]
I want to leave this open if you don't mind because I would like to eventually implement your solution of caching the TypeScript instance on the webpack compiler, or at least try to implement some way to detect the issue and warn the issue. This has come up a couple times and seems like a common enough scenario to address.
