### ISSUE TITLE
Issue with the webpack require function

### ISSUE THREAD

**Issue by jusefb** [TypeStrong/ts-loader#98]
Hi,

I was trying to use the require function in my declaration file but using the function described in docs throws multiple errors:

```javascript
declare var require: {
    <T>(path: string): T;
    (paths: string[], callback: (...modules: any[]) => void): void;
    ensure: (paths: string[], callback: (require: <T>(path: string) => T) => void) => void;
};
```
Could you explain to me what I am doing wrong?

Kind regards

Jusef

**Comment by jusefb** [comment]
I think I have managed to make it work. One thing I have had to do is to declare the require call as a simple function that requires a string parameter and can be anything.

```javascript
declare function require(string): any;
```

**Comment by jbrantly** [comment]
In the definitions for `require` that I provide you should pass in the generic type parameter to appropriately type the result. If you do not then it will be typed as `{}` which is why you were getting those errors.

In your definition you're just explicitly typing the result as `any`.

If you went back to the original definitions you could achieve the same result by using:
```typescript
var foo = require<any>('foo');
```

**Comment by jusefb** [comment]
Ok, that makes sense. Thank you very much for the explanation.

**Comment by jbrantly** [comment]
No problem! Glad you got it working one way or another :grin:
