### ISSUE TITLE
Named imported module used only for typings is wrongly excluded from the bundle

### ISSUE THREAD

**Issue by KableM** [TypeStrong/ts-loader#986]
This is despite setting `sideEffects: true` in `package.json` which should prevent webpack from pruning unused imports. As an extended measure I set `optimizations.sideEffects` to false in `webpack.config.js` to  ensure webpack wouldn't prune unused imports. 

A similar setup with vanilla JS correctly includes the file in the bundle, which is why I created the issue here and not the webpack repo.

I've created a sample project which exhibits the issue:
https://github.com/KableM/webpack-ts-loader-bug

I checked in the dist folder so you can see what my setup produced, but feel free to try for yourself:

    git clone https://github.com/KableM/webpack-ts-loader-bug.git
    cd webpack-ts-loader-bug
    npm install; npm run build

This creates 4 bundles in the dist/ folder representing 4 scenarios:

* **A** `main1.bundle.js`: Named import used for typings only, module excluded from the bundle
* **B** `main2.bundle.js`: Named import used for typings and code execution, module included in the bundle
* **C** `main3.bundle.js`: Import file only, module included in the bundle
* **D** `main1-vanillajs.bundle.js`: Vanilla JS named import that isn't used, module included in the bundle

Shouldn't scenario A include the module as what happens in the other scenarios?
Apologies if I'm missing something

**Comment by johnnyreilly** [comment]
So as I understand it, you're happy with the behaviour of scenarios B,C and D but you'd rather A included the typings on emit?

And it's really the typings being included that's the issue?

I'm not sure how this would be handled well.... Typings only exist at compile time and so from webpacks perspective it seems legitimate that they are not included. Remember, webpack is all about the js. It's not about the types.

It feels like this is probably "correct" behaviour. I always find it easier to understand an issue with a concrete example in hand. "This is problematic because...."

What's your pain here? What's the need that the current behaviour doesn't support

**Comment by KableM** [comment]
I guess the problem isn't that "typings" need to be imported, the file itself needs to be imported to ensure this "side-effect" code is run `customElements.define("my-web-component", MyWebComponent);`. You're right, I only need the typings at compile time but I need that particular line at runtime.
